name: menu_editor
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.14.0 <3.0.0'

fonts:
- family: sficonsets
  fonts:
    - asset: packages/flutter_sfsymbols/fonts/sficonsets.ttf

dependencies:
  flutter:
    sdk: flutter

  # common
  uuid: ^3.0.4

  # get
  get: ^4.3.0
  get_storage: ^2.0.3

  # networking
  json_serializable: any

  # ui
  google_fonts: ^2.1.0
  menubar:
    path: ./plugins/menubar
  window_size:
    path: ./plugins/window_size
  menu_clt:
    path: ./menu_clt
  file_picker: any
  flutter_sfsymbols: ^2.0.0
  expandable: ^5.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any

flutter:
  uses-material-design: true

# install derry from https://pub.dev/packages/derry
scripts:
  build: flutter pub run build_runner build --delete-conflicting-outputs
